#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]


def hx_to_int(value) -> int:
    if isinstance(value, int):
        return value
    return int(str(value), 16)


def sanitize_component(name: str) -> str:
    name = name.replace("\\", "/").split("/")[-1] if name in {"", ".", ".."} else name
    name = re.sub(r"[^A-Za-z0-9_.+-]+", "_", name)
    name = name.strip("._")
    if not name:
        name = "unnamed"
    return name[:120]


def sanitize_relpath(path: str) -> Path:
    path = path.replace("\\", "/")
    path = re.sub(r"^[A-Za-z]:/", "", path)
    path = path.lstrip("/")

    parts = []
    for part in path.split("/"):
        if not part or part in {".", ".."}:
            continue
        parts.append(sanitize_component(part))

    if not parts:
        parts = ["unknown.cpp"]

    return Path(*parts)


def source_to_target_stem(source_path: str) -> Path:
    rel = sanitize_relpath(source_path)

    # CWLib/BinkVideo.cpp -> CWLib/BinkVideo
    if rel.suffix:
        rel = rel.with_suffix("")

    return rel


def code_section_for_symbol(symbol: str) -> str:
    # Original PPC64 code symbols are dot-prefixed:
    #   ._Z8BinkInitv
    # GCC -ffunction-sections usually emits section:
    #   .text._Z8BinkInitv
    name = symbol[1:] if symbol.startswith(".") else symbol
    if not name:
        name = "unknown"
    return f".text.{name}"


def emit_ppc_words(out, blob: bytes) -> None:
    whole = len(blob) & ~3

    for i in range(0, whole, 4):
        word = int.from_bytes(blob[i:i + 4], "big")
        out.write(f"    .4byte 0x{word:08x}\n")

    for b in blob[whole:]:
        out.write(f"    .byte 0x{b:02x}\n")


def read_bytes(path: Path, offset: int, size: int) -> bytes:
    with path.open("rb") as f:
        f.seek(offset)
        data = f.read(size)

    if len(data) != size:
        raise RuntimeError(
            f"short read from {path}: offset=0x{offset:x}, "
            f"wanted=0x{size:x}, got=0x{len(data):x}"
        )

    return data


def make_unique_label(symbol: str, addr: int, symbol_counts: dict[str, int]) -> tuple[str, bool]:
    """
    Returns (label_name, should_global).

    If a symbol only occurs once in this generated object, preserve it exactly.
    If it occurs more than once, use an address-based private label to avoid
    assembler duplicate-symbol errors.
    """
    if symbol_counts.get(symbol, 0) <= 1:
        return symbol, True

    # Local/address-unique fallback. Do not export as global.
    return f".L_objdiff_{addr:08x}", False


def section_for_function(symbol: str, addr: int, symbol_counts: dict[str, int]) -> str:
    """
    For unique symbols, mimic the source object's function-section naming.
    For duplicate local/static names, use an address-unique section so multiple
    same-named functions do not merge into one input section.
    """
    if symbol_counts.get(symbol, 0) > 1:
        return f".text.objdiff_{addr:08x}"

    return code_section_for_symbol(symbol)


def emit_source_target_asm(
    elf_path: Path,
    source_path: str,
    source_info: dict,
    asm_path: Path,
) -> int:
    funcs = source_info.get("functions", [])
    funcs = sorted(funcs, key=lambda f: hx_to_int(f["addr"]))

    asm_path.parent.mkdir(parents=True, exist_ok=True)

    symbol_counts: dict[str, int] = {}
    for fn in funcs:
        symbol = fn.get("symbol", "")
        if symbol:
            symbol_counts[symbol] = symbol_counts.get(symbol, 0) + 1

    # Keep the path relative to repo root, because make runs assembler from repo root.
    try:
        incbin_elf_path = elf_path.relative_to(ROOT).as_posix()
    except ValueError:
        incbin_elf_path = elf_path.as_posix()

    with asm_path.open("w") as out:
        out.write("/* Auto-generated by tools/gen_objdiff_targets.py. Do not edit. */\n")
        out.write(f"/* original source: {source_path} */\n\n")

        emitted = 0
        renamed = 0

        for fn in funcs:
            symbol = fn.get("symbol", "")
            if not symbol:
                continue

            addr = hx_to_int(fn["addr"])
            offset = hx_to_int(fn["offset"])
            size = hx_to_int(fn["size"])

            if size <= 0:
                continue

            label, is_global = make_unique_label(symbol, addr, symbol_counts)
            section = section_for_function(symbol, addr, symbol_counts)

            out.write(
                f"/* {symbol} addr=0x{addr:x} "
                f"offset=0x{offset:x} size=0x{size:x}"
            )

            if label != symbol:
                out.write(f" label={label}")

            out.write(" */\n")
            out.write(f'.section {section}, "ax", @progbits\n')

            if is_global:
                out.write(f".global {label}\n")
            else:
                out.write(f".local {label}\n")
                renamed += 1

            out.write(f"{label}:\n")
            out.write(f'    .incbin "{incbin_elf_path}", {offset}, {size}\n')
            out.write("\n")

            emitted += 1

    if renamed:
        print(f"{source_path}: renamed {renamed} duplicate local/static symbol(s)")

    return emitted


def main() -> int:
    db_path = ROOT / "build" / "decomp_db.json"
    elf_path = ROOT / "orig" / "EBOOT.ELF"

    if not db_path.exists():
        raise RuntimeError("missing build/decomp_db.json; run tools/build_decomp_db.py first")

    if not elf_path.exists():
        raise RuntimeError("missing orig/EBOOT.ELF")

    db = json.loads(db_path.read_text())
    sources = db.get("sources", {})

    asm_root = ROOT / "asm" / "objdiff" / "target"
    obj_root = ROOT / "build" / "objdiff" / "target"
    targets_json_path = ROOT / "build" / "objdiff" / "targets.json"

    asm_root.mkdir(parents=True, exist_ok=True)
    obj_root.mkdir(parents=True, exist_ok=True)
    targets_json_path.parent.mkdir(parents=True, exist_ok=True)

    targets = []
    total_funcs = 0

    for source_path, source_info in sorted(sources.items()):
        funcs = source_info.get("functions", [])
        if not funcs:
            continue

        stem = source_to_target_stem(source_path)

        asm_path = asm_root / stem.with_suffix(".s")
        obj_path = obj_root / stem.with_suffix(".o")

        emitted = emit_source_target_asm(
            elf_path=elf_path,
            source_path=source_path,
            source_info=source_info,
            asm_path=asm_path,
        )

        if emitted == 0:
            continue

        total_funcs += emitted

        targets.append({
            "source": source_path,
            "asm": asm_path.relative_to(ROOT).as_posix(),
            "obj": obj_path.relative_to(ROOT).as_posix(),
            "functions": emitted,
        })

    targets_json_path.write_text(json.dumps(targets, indent=2) + "\n")

    print(f"wrote {targets_json_path}")
    print(f"target source files: {len(targets)}")
    print(f"target functions: {total_funcs}")

    for t in targets[:30]:
        print(f"{t['source']} -> {t['obj']} ({t['functions']} funcs)")

    if len(targets) > 30:
        print(f"... {len(targets) - 30} more")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())